name: get
description: Reactive and simple state management with dependency injection for Flutter, based on GetX.
version: 5.0.0-release-candidate-9.3.3
homepage: https://github.com/jonataslaw/getx

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
